CREATE DATABASE uniprofile;
CREATE TABLE `uniprofile`.`profiles`
(
`fname` TEXT NULL ,
`mname` TEXT NULL ,
`lname` TEXT NULL ,
`phone1` TEXT NULL ,
`phone2` TEXT NULL ,
`phone3` TEXT NULL ,
`email1` TEXT NULL ,
`email2` TEXT NULL ,
`email3` TEXT NULL ,
`gender` TEXT NULL ,
`byr` INT NULL ,
`bmnth` INT NULL ,
`bday` INT NULL ,
`addrnum1` INT NULL ,
`dir1` TEXT NULL ,
`stname1` TEXT NULL ,
`sttype1` TEXT NULL ,
`aptnum1` INT NULL ,
`city1` TEXT NULL ,
`state1` TEXT NULL ,
`zip1` INT NULL ,
`addrnum2` INT NULL ,
`dir2` TEXT NULL ,
`stname2` TEXT NULL ,
`sttype2` TEXT NULL ,
`aptnum2` INT NULL ,
`city2` TEXT NULL ,
`state2` TEXT NULL ,
`zip2` INT NULL ,
`school1` TEXT NULL ,
`gpa1` DOUBLE NULL ,
`mjr11` TEXT NULL ,
`mjr12` TEXT NULL ,
`min11` TEXT NULL ,
`min12` TEXT NULL ,
`school2` TEXT NULL ,
`gpa2` DOUBLE NULL ,
`mjr21` TEXT NULL ,
`mjr22` TEXT NULL ,
`min21` TEXT NULL ,
`min22` TEXT NULL ,
`school3` TEXT NULL ,
`gpa3` DOUBLE NULL ,
`mjr31` TEXT NULL ,
`mjr32` TEXT NULL ,
`min31` TEXT NULL ,
`min32` TEXT NULL
)
ENGINE = MyISAM CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;